# Generated by Django 4.0.3 on 2022-04-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/images', max_length=200),
        ),
    ]
